c*************************************************************************
c                        ODEA.INC
c*************************************************************************
C Include file for the parameters

c...   Criteria for hierarchy changes and close encounters
       real*8 CRITCHANGE, CRITCE
       parameter (CRITCHANGE = 0.2, CRITCE = 0.001)

c-------------------------------------------------------------------------
